{
  "timestamp": "2025-10-29T08:07:32.554573",
  "uptime_hours": 0.0022567747222222226,
  "total_components": 4,
  "component_status": {
    "error": 4
  },
  "total_restarts": 0,
  "error_count": 0,
  "system_metrics": null,
  "component_details": {
    "autonomous_testing": {
      "name": "autonomous_testing",
      "status": "ComponentStatus.ERROR",
      "pid": 18952,
      "cpu_percent": 0.0,
      "memory_mb": 0.0,
      "uptime_seconds": 0.0,
      "restart_count": 0,
      "last_error": "進程退出，返回碼: 1",
      "timestamp": "2025-10-29 08:07:24.437276"
    },
    "system_explorer": {
      "name": "system_explorer",
      "status": "ComponentStatus.ERROR",
      "pid": 23096,
      "cpu_percent": 0.0,
      "memory_mb": 0.0,
      "uptime_seconds": 0.0,
      "restart_count": 0,
      "last_error": "啟動失敗: usage: ai_system_explorer_v3.py [-h] [--workspace WORKSPACE] [--detailed]\n                                [--force-professional] [--output OUTPUT]\nai_system_explorer_v3.py: error: unrecognized arguments: --continuous-mode\n",
      "timestamp": "2025-10-29 08:07:26.509931"
    },
    "security_monitor": {
      "name": "security_monitor",
      "status": "ComponentStatus.ERROR",
      "pid": 6968,
      "cpu_percent": 0.0,
      "memory_mb": 0.0,
      "uptime_seconds": 0.0,
      "restart_count": 0,
      "last_error": "啟動失敗: None",
      "timestamp": "2025-10-29 08:07:28.521485"
    },
    "functionality_validator": {
      "name": "functionality_validator",
      "status": "ComponentStatus.ERROR",
      "pid": 4428,
      "cpu_percent": 0.0,
      "memory_mb": 0.0,
      "uptime_seconds": 0.0,
      "restart_count": 0,
      "last_error": "啟動失敗: None",
      "timestamp": "2025-10-29 08:07:30.540939"
    }
  }
}